# Generated by Django 5.1.3 on 2024-11-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(null=True, verbose_name="Date of birth"),
        ),
    ]
