# Generated by Django 5.1.3 on 2024-11-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicearea",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name of Law"),
        ),
    ]
