# Generated by Django 5.1.3 on 2024-11-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_practicearea_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="practicearea",
            constraint=models.UniqueConstraint(fields=("name",), name="pa_name_unq"),
        ),
    ]
