# Generated by Django 5.1.3 on 2024-11-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_practicearea_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicearea",
            options={
                "verbose_name": "Practice Area",
                "verbose_name_plural": "Practice Areas",
            },
        ),
    ]
