# Generated by Django 5.1.3 on 2024-11-22 05:16

from django.db import migrations


def practicarea_load_initial_data(apps, schemas):
    PracticeArea = apps.get_model("appointments", "PracticeArea")
    PracticeArea.objects.create(
        name="Test Law",
        description="test description"
    )



class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_practicearea_options"),
    ]

    operations = [
        migrations.RunPython(practicarea_load_initial_data)
    ]
